spring:
  profiles:
    # 默认环境
    active: dev
  application:
    name: user-center
  # DataSource Config
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/lu
#    username: root
#    password: 123456
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/lu?serverTimezone=Asia/Shanghai
      username: root
      password: 123456
      initial-size: 5
      max-active: 50
      max-wait: 5000
      #最小空闲值.当空闲的连接数少于阀值时，连接池就会预申请去一些连接，以免洪峰来时来不及申请。
      min-idle: 5

  # session超时时间
  session:
    timeout: 86400
  mvc:
    # Springboot2.6以后 MVC 默认匹配改变, 导致整合 swagger会报错找不到
    # 需要手动指定匹配策略 ANT_PATH_MATCHER
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  redis:
    host:
    port:
    password:
    # Redis默认提供了16个数据库，此处的0表示选择0号数据库
    database: 0
    jedis:
      # Redis连接池配置
      pool:
        max-active: 8  # 最大连接数
        max-wait: 1ms  # 连接池最大阻塞等待时间
        max-idle: 4  # 连接池中的最大空闲连接
        min-idle: 0  # 连接池中的最小空闲连接
server:
  port: 8079
  servlet:
    context-path: /api
    session:
      cookie:
        secure: false

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 开启逻辑删除自动判断
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
yuapi:
  client:
    access-key:
    secret-key:
deer:
  chatType:
  # 登录白名单
  whitelistDeerCode:

